### ISSUE TITLE
Release v0.4.0

### ISSUE THREAD

**Issue by kbarbary** [sncosmo/sncosmo#20]
To do list before v0.4.0 is released:
- [x] [API] How should the result of `fit_lc()` be structured? _Finalized_
- [x] [API] Should `plot_lc()` return a `Figure` object (like triangle.corner does)? _Yes_
- [x] [API] Should `ObsModel` just be `Model` (it's the main entry point for models...)? _Yes, at least for RC_
- [x] [API] Change name of `'csv'` format in `read_lc()` and `write_lc()` _changed to 'ascii'_
- [x] [API] Should models not have a `wavelength` and `phase` attribute? (related to #14) _No; now removed!_
- [x] [API] `nest_lc()` should return samples' `prior` and `likelihood` separately (also, add `dof`)
- [x] [API] Add `model_label` keyword to `plot_lc()` and `label` to `animate_model()`
- [x] [DOC] Documentation needs updating and extending.
- [ ] [TEST] Need much more extensive unit tests. (#3)
- [ ] [FEATURE] SALT2 dispersion model (#6 and #4)
- [x] [FEATURE] Update or temporarily remove `PhotoTyper` _Temporarily removed. There are too many uncertainties in the path to a good API._
- [ ] [FEATURE] More robust wavelength bounds (`minwave()`, `maxwave()`) in `Model`
- [ ] [FEATURE] Model data hosted on disk instead of remotely?
- [x] [FEATURE] More robust nested sampling algorithm _Determined that single-modal nest is good enough._
- [x] [FEATURE] Add `simulate_vol` function (marked as experimental) _Done_
