### ISSUE TITLE
Release v0.5.0

### ISSUE THREAD

**Issue by kbarbary** [sncosmo/sncosmo#55]
This is a meta-issue to track issues needed for v0.5.0 release. 

- [x] Refactor `get_ebv_from_map` using a new `SFD98Map` class [#29]
- [x] Improve `pdf_to_ppf`[#25]
- [x] Increase test coverage [#3] - See https://coveralls.io/r/sncosmo/sncosmo for areas needing tests.
- [x] Python 3 compatibility [#1] - Implemented in #54 but need Iminuit to support Python 3.
- [x] In the docs, make plots of built-in filters better looking.
- [x] Document use of `get_ebv_from_map()` in model docs.
- [x] Make `fit_lc` and `nest_lc` results consistent [#30]
- [x] Refactor data fetching system [#5] - Implemented in #73
- [x] Clean up any remaining TODO comments in code
- [x] Update docs on data fetching system, starting from #73 text
- [x] Update `mcmc_lc()` arguments & docstring.
- [x] resolve #69 / #72

**Comment by rbiswas4** [comment]
I would like to see documentation on how to run SNCosmo fitting on parallel systems (CONDOR and MPI) using other utilities.

**Comment by kbarbary** [comment]
@rbiswas4 Me too!

**Comment by kbarbary** [comment]
@rbiswas4 Milky Way dust treatment is now in the docs here: 
http://sncosmo.readthedocs.org/en/latest/models.html#adding-milky-way-dust

**Comment by rbiswas4** [comment]
So, what about CCM. I thought you said one was supposed to use both,
simultaneously?

**Comment by kbarbary** [comment]
The `CCM89Dust` propagation effect is used in the first line of the example. The dust law becomes part of the model itself.

**Comment by rbiswas4** [comment]
@kbarbary 
Ah sorry, I had missed that.

But I do not completely understand what is going on: So to split this up
1. As stated, you have defined dust in both the observer frame and rest frame and so there are two kinds of dust here MW dust and host dust. 
2. When you set mewbv, I am guessing the class knows that this is for the mw dust component? But what happens to the host dust component? Is there a hidden hostebv parameter which is set to zero by default?

**Comment by kbarbary** [comment]
Yep, you've got it right.

I wouldn't exactly say that the `hostebv` parameter is "hidden" though:
```
>>> model.param_names
['z', 't0', 'amplitude', 'hostebv', 'hostr_v', 'mwebv', 'mwr_v']
```

The section directly above (http://sncosmo.readthedocs.org/en/latest/models.html#creating-a-model-with-a-source-and-effect-s) is meant to illustrate how effect parameters are combined into the model. Perhaps the link to that section should be made more explicit in the text.

**Comment by rbiswas4** [comment]
OK, good .... I will think more about it.

**Comment by kbarbary** [comment]
Updated the doc section based on your feedback.
