### ISSUE TITLE
Tracking Issue

### ISSUE THREAD

**Issue by kbarbary** [sncosmo/sncosmo#79]
This is a meta-issue to categorize outstanding features.

## Major new features

- [ ] creating new spectral timeseries [#56]
- [x] MLCS2k2 model [#81]

## Precision

_Issues necessary for sncosmo to be a full replacement for snfit_

- [x] Position-dependent bandpasses [#10]
- [x] Covariance in photometric data [#4]
- [x] Color-dependent bandpasses
- [ ] thoroughly test against snfit [#78]

## Enhancements

- [ ] Model extrapolation in time [#7]

## Straight-forward enhancements

- [x] photometric data column aliases in simulations [#70]

## Documentation

- [ ] Page on plotting
- [ ] Expand fitting page with mcmc and nest examples.

**Comment by rbiswas4** [comment]
Of these issues, position dependent and color dependent bandpasses seem the most important to me. I think the bulk of the nice capabilities that SNCosmo has is in the area of light curve fitting, but the lack of such bandpasses would make it difficult to actually analyze real data and get real answers in many cases.

**Comment by kbarbary** [comment]
Closing this tracking issue in favor of just using the issue tracker and milestones (v1.5.0 currently).
